version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    container_name: BookScrapeDB
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/literature123
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - ./data:/var/lib/neo4j/import
      - ./logs:/logs
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  production:
    driver: bridge
  development:
    driver: bridge